  CREATE TABLE "SYSTEM"."EMP_DETAILS" 
   (	"NIC" VARCHAR2(15 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"ADDRESS1" VARCHAR2(100 BYTE), 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"POSTALCODE" VARCHAR2(10 BYTE), 
	"CONTACTNUMBER" VARCHAR2(10 BYTE)
   )